use crate::{BridgeFaultCode, ProtocolError};
use dmc2_hal_sys as hal;

hal::userspace_hal_output_catalog! {
    pub(super) struct HalPins;
    error = super::registration::RegistrationError;
    register = super::registration::output_pin;
    snapshot_generation: u32 => "snapshot-generation";
    connected: bit => "connected";
    serial_fault: bit => "serial-fault";
    quadrature_fault: bit => "quadrature-fault";
    link_healthy: bit => "link-healthy";
    heartbeat: bit => "heartbeat";
    estop_pressed: bit => "estop-pressed";
    deadman_held: bit => "deadman-held";
    selector_valid: bit => "selector-valid";
    axis: bit[7] => ["axis-x", "axis-y", "axis-z", "axis-4", "axis-5", "axis-off", "axis-invalid"];
    multiplier: bit[5] => ["multiplier-x1", "multiplier-x10", "multiplier-x100", "multiplier-off", "multiplier-invalid"];
    axis_code: s32 => "axis-code";
    multiplier_code: s32 => "multiplier-code";
    latest_detent: s32 => "latest-detent";
    detent_count: s32 => "detent-count";
    transition_count: s32 => "transition-count";
    quadrature_errors: u32 => "quadrature-errors";
    sequence: u32 => "sequence";
    milliseconds: u32 => "milliseconds";
    protocol_errors: u32 => "protocol-errors";
    dropped_packets: u32 => "dropped-packets";
    timeouts: u32 => "timeouts";
    packet_age_ms: float => "packet-age-ms";
    bridge_fault_valid: bit => "bridge-fault-valid";
    bridge_fault_kind: bit[BridgeFaultCode::COUNT] => BridgeFaultCode::ALL.map(|fault| format!("fault-kind-{}", fault.wire_code()));
    bridge_fault_code: s32 => "bridge-fault-code";
    bridge_fault_protocol_error_valid: bit => "fault-data-b00";
    bridge_fault_protocol_error_kind: bit[ProtocolError::COUNT] => ProtocolError::ALL.map(|error| format!("fault-protocol-kind-{}", error.wire_code()));
    bridge_fault_protocol_error_code: s32 => "fault-data-s00";
    bridge_fault_line_bytes_valid: bit => "fault-data-b01";
    bridge_fault_previous_sequence_valid: bit => "fault-data-b02";
    bridge_fault_observed_sequence_valid: bit => "fault-data-b03";
    bridge_fault_packet_age_valid: bit => "fault-data-b04";
    bridge_fault_timeout_valid: bit => "fault-data-b05";
    bridge_fault_previous_quadrature_errors_valid: bit => "fault-data-b06";
    bridge_fault_observed_quadrature_errors_valid: bit => "fault-data-b07";
    bridge_fault_operating_system_error_valid: bit => "fault-data-b08";
    bridge_fault_transport_contract_result_valid: bit => "fault-data-b09";
    bridge_fault_line_bytes: u32 => "fault-data-u00";
    bridge_fault_previous_sequence: u32 => "fault-data-u01";
    bridge_fault_observed_sequence: u32 => "fault-data-u02";
    bridge_fault_previous_quadrature_errors: u32 => "fault-data-u03";
    bridge_fault_observed_quadrature_errors: u32 => "fault-data-u04";
    bridge_fault_transport_contract_result_low: u32 => "fault-data-u05";
    bridge_fault_transport_contract_result_high: u32 => "fault-data-u06";
    bridge_fault_packet_age_ms: float => "fault-data-f00";
    bridge_fault_timeout_ms: float => "fault-data-f01";
    bridge_fault_operating_system_error: s32 => "fault-data-s01";
    last_protocol_error_valid: bit => "last-protocol-error-valid";
    last_protocol_error_kind: bit[ProtocolError::COUNT] => ProtocolError::ALL.map(|error| format!("last-pe-kind-{}", error.wire_code()));
    last_protocol_error_code: s32 => "last-protocol-error-code";
    last_protocol_error_line_bytes_valid: bit => "last-pe-data-b00";
    last_protocol_error_previous_sequence_valid: bit => "last-pe-data-b01";
    last_protocol_error_observed_sequence_valid: bit => "last-pe-data-b02";
    last_protocol_error_line_bytes: u32 => "last-pe-data-u00";
    last_protocol_error_previous_sequence: u32 => "last-pe-data-u01";
    last_protocol_error_observed_sequence: u32 => "last-pe-data-u02";
}
