use dmc2_hal_sys as hal;

pub(in crate::component) struct Pins {
    pub(super) pendant_snapshot_generation: *mut hal::hal_u32_t,
    pub(super) connected: *mut hal::hal_bit_t,
    pub(super) serial_fault: *mut hal::hal_bit_t,
    pub(super) quadrature_fault: *mut hal::hal_bit_t,
    pub(super) estop_pressed: *mut hal::hal_bit_t,
    pub(super) deadman_held: *mut hal::hal_bit_t,
    pub(super) selector_valid: *mut hal::hal_bit_t,
    pub(super) axis_code: *mut hal::hal_s32_t,
    pub(super) multiplier_code: *mut hal::hal_s32_t,
    pub(super) latest_detent: *mut hal::hal_s32_t,
    pub(super) detent_count: *mut hal::hal_s32_t,
    pub(super) transition_count: *mut hal::hal_s32_t,
    pub(super) quadrature_errors: *mut hal::hal_u32_t,
    pub(super) sequence: *mut hal::hal_u32_t,
    pub(super) milliseconds: *mut hal::hal_u32_t,

    pub(super) task_snapshot_generation: *mut hal::hal_u32_t,
    pub(super) task_monitor_connected: *mut hal::hal_bit_t,
    pub(super) task_monitor_fault: *mut hal::hal_bit_t,
    pub(super) task_heartbeat: *mut hal::hal_u32_t,
    pub(super) machine_on: *mut hal::hal_bit_t,
    pub(super) estopped: *mut hal::hal_bit_t,
    pub(super) manual_mode: *mut hal::hal_bit_t,
    pub(super) joint_mode: *mut hal::hal_bit_t,
    pub(super) teleop_mode: *mut hal::hal_bit_t,
    pub(super) interp_idle: *mut hal::hal_bit_t,
    pub(super) joint_homed: [*mut hal::hal_bit_t; 3],
    pub(super) joint_homing: [*mut hal::hal_bit_t; 3],
    pub(super) axis_stopped: [*mut hal::hal_bit_t; 3],

    pub(super) motor_count: [*mut hal::hal_s32_t; 3],
    pub(super) motor_position_feedback: [*mut hal::real_t; 3],
    pub(super) motor_limit_raw: [*mut hal::hal_bit_t; 3],
    pub(super) motor_limit_latched: [*mut hal::hal_bit_t; 3],
    pub(super) pendant_mode_enabled: *mut hal::hal_bit_t,
    pub(super) servo_thread_ready: *mut hal::hal_bit_t,
    pub(super) mesa_watchdog_has_bit: *mut hal::hal_bit_t,
    pub(super) mesa_packet_error: *mut hal::hal_bit_t,
    pub(super) mesa_packet_error_total: *mut hal::hal_u32_t,
    pub(super) mesa_packet_error_exceeded: *mut hal::hal_bit_t,
    pub(super) software_watchdog_ok: *mut hal::hal_bit_t,
    pub(super) ui_ready: *mut hal::hal_bit_t,

    pub(super) motor_limit_reset: [*mut hal::hal_bit_t; 3],
    pub(super) motor_command_enable: [*mut hal::hal_bit_t; 3],
    pub(super) motor_toward_limit: [*mut hal::hal_bit_t; 3],
    pub(super) external_enable: *mut hal::hal_bit_t,
    pub(super) watchdog_enable: *mut hal::hal_bit_t,
    pub(super) heartbeat: *mut hal::hal_bit_t,
    pub(super) position_known: *mut hal::hal_bit_t,
    pub(super) position_unknown: *mut hal::hal_bit_t,
    pub(super) control_available: *mut hal::hal_bit_t,
    pub(super) control_ready: *mut hal::hal_bit_t,
    pub(super) fault: *mut hal::hal_bit_t,
    pub(super) fault_code: *mut hal::hal_s32_t,
    pub(super) recovery_active: *mut hal::hal_bit_t,
    pub(super) jog_active: *mut hal::hal_bit_t,
    pub(super) bounce_active: *mut hal::hal_bit_t,
    pub(super) supervisor_phase: *mut hal::hal_s32_t,
    pub(super) mesa_phase: *mut hal::hal_s32_t,
    pub(super) controller_watchdog_phase: *mut hal::hal_s32_t,
    pub(super) estop_reset_request: *mut hal::hal_bit_t,
    pub(super) machine_on_request: *mut hal::hal_bit_t,

    pub(super) axis_increment_plus: [*mut hal::hal_bit_t; 3],
    pub(super) axis_increment_minus: [*mut hal::hal_bit_t; 3],
    pub(super) joint_increment_plus: [*mut hal::hal_bit_t; 3],
    pub(super) joint_increment_minus: [*mut hal::hal_bit_t; 3],
    pub(super) axis_increment: [*mut hal::real_t; 3],
    pub(super) joint_increment: [*mut hal::real_t; 3],
    pub(super) axis_jog_speed: *mut hal::real_t,
    pub(super) joint_jog_speed: *mut hal::real_t,
    pub(super) jog_stop: *mut hal::hal_bit_t,
    pub(super) jog_stop_immediate: *mut hal::hal_bit_t,
    pub(super) command_phase: *mut hal::hal_s32_t,
}
