[workspace]
resolver = "2"
members = [
    "crates/dmc2-core",
    "crates/dmc2-hal-sys",
    "crates/dmc2-linuxcnc-interface",
    "crates/dmc2-launcher",
    "crates/dmc2-rt",
    "crates/dmc2-serial-bridge",
    "crates/dmc2-task-monitor",
]

[workspace.package]
edition = "2021"
license = "MIT"
rust-version = "1.85"

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
lto = true
overflow-checks = true
panic = "abort"
